"""add_profile_fields_to_user

Revision ID: 047831663084
Revises: bb94b2777895
Create Date: 2025-09-13 16:12:59.497266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '047831663084'
down_revision: Union[str, Sequence[str], None] = 'bb94b2777895'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('users', sa.Column('bio', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('social_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('featured_strategy_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('featured_post_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'community_posts', ['featured_post_id'], ['id'])
    op.create_foreign_key(None, 'users', 'strategies', ['featured_strategy_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'featured_post_id')
    op.drop_column('users', 'featured_strategy_id')
    op.drop_column('users', 'social_links')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'bio')
   
    # ### end Alembic commands ###
