"""add_ai_model_version_and_retraining_fields

Revision ID: 447f767524e1
Revises: 579d1c31faaa
Create Date: 2025-12-23 08:15:29.458529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '447f767524e1'
down_revision: Union[str, Sequence[str], None] = '579d1c31faaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_model_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('training_start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('training_end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_weights_path', sa.String(length=500), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['ai_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id', 'version_number', name='_model_version_uc')
    )
    op.create_index(op.f('ix_ai_model_versions_model_id'), 'ai_model_versions', ['model_id'], unique=False)
    
    op.add_column('ai_models', sa.Column('is_auto_retrain_enabled', sa.Boolean(), nullable=False))
    op.add_column('ai_models', sa.Column('retrain_interval_days', sa.Integer(), nullable=True))
    op.add_column('ai_models', sa.Column('retrain_data_window_days', sa.Integer(), nullable=True))
    op.add_column('ai_models', sa.Column('next_retrain_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ai_models', sa.Column('active_version_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_ai_models_active_version_id', 'ai_models', 'ai_model_versions', ['active_version_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_ai_models_active_version_id', 'ai_models', type_='foreignkey')
    op.drop_column('ai_models', 'active_version_id')
    op.drop_column('ai_models', 'next_retrain_at')
    op.drop_column('ai_models', 'retrain_data_window_days')
    op.drop_column('ai_models', 'retrain_interval_days')
    op.drop_column('ai_models', 'is_auto_retrain_enabled')
    op.drop_index(op.f('ix_ai_model_versions_model_id'), table_name='ai_model_versions')
    op.drop_table('ai_model_versions')
    # ### end Alembic commands ###
