"""add_ai_model_to_enum

Revision ID: 579d1c31faaa
Revises: 932672958d5b
Create Date: 2025-12-23 07:46:28.610843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '579d1c31faaa'
down_revision: Union[str, Sequence[str], None] = '932672958d5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted manually ###
    # Postgres Enum 타입에 새로운 값 'AI_MODEL' 추가
    op.execute("ALTER TYPE producttype ADD VALUE IF NOT EXISTS 'AI_MODEL'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
