"""Descriptive message about your changes

Revision ID: 5d73c541547e
Revises: ca8c1abe5839
Create Date: 2025-12-01 00:02:13.809011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d73c541547e'
down_revision: Union[str, Sequence[str], None] = 'ca8c1abe5839'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('live_bots', sa.Column('execution_interval', sa.String(length=20), nullable=False))
    op.add_column('live_bots', sa.Column('trailing_stop_config', sa.JSON(), nullable=True))
    op.create_foreign_key('fk_users_featured_strategy_id', 'users', 'strategies', ['featured_strategy_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_featured_strategy_id', 'users', type_='foreignkey')
    op.drop_column('live_bots', 'trailing_stop_config')
    op.drop_column('live_bots', 'execution_interval')
    # ### end Alembic commands ###
