"""Descriptive message about your changes

Revision ID: 62a30a43a991
Revises: bfd1b2984984
Create Date: 2025-12-02 19:20:30.942339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '62a30a43a991'
down_revision: Union[str, Sequence[str], None] = 'bfd1b2984984'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('live_bots', sa.Column('equity', sa.Float(), nullable=True, comment='총 자산 (현금 + 미실현 손익)'))
    op.create_foreign_key('fk_users_featured_strategy_id', 'users', 'strategies', ['featured_strategy_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_featured_strategy_id', 'users', type_='foreignkey')
    op.drop_column('live_bots', 'equity')
    # ### end Alembic commands ###
