"""add_ai_epoch

Revision ID: 6f11954e9c88
Revises: 447f767524e1
Create Date: 2025-12-24 04:01:12.934791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f11954e9c88'
down_revision: Union[str, Sequence[str], None] = '447f767524e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_training_jobs', sa.Column('epoch_logs', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_training_jobs', 'epoch_logs')
    # ### end Alembic commands ###
