"""add_profile_fields_to_user

Revision ID: 8623cc6bf52d
Revises: 047831663084
Create Date: 2025-09-13 18:18:12.990801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8623cc6bf52d'
down_revision: Union[str, Sequence[str], None] = '047831663084'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('user_inventory', sa.Column('quantity', sa.Integer(), server_default='1', nullable=False))
    op.add_column('user_inventory', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_user_inventory_is_used'), table_name='user_inventory')
    op.create_unique_constraint('_user_product_uc', 'user_inventory', ['user_id', 'product_id'])
    op.drop_constraint(op.f('user_inventory_order_item_id_fkey'), 'user_inventory', type_='foreignkey')
    op.drop_column('user_inventory', 'is_used')
    op.drop_column('user_inventory', 'order_item_id')
    op.drop_column('user_inventory', 'used_at')
    op.drop_constraint(op.f('users_featured_post_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'featured_post_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('featured_post_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_featured_post_id_fkey'), 'users', 'community_posts', ['featured_post_id'], ['id'])
    op.add_column('user_inventory', sa.Column('used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('user_inventory', sa.Column('order_item_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('user_inventory', sa.Column('is_used', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('user_inventory_order_item_id_fkey'), 'user_inventory', 'marketplace_order_items', ['order_item_id'], ['id'])
    op.drop_constraint('_user_product_uc', 'user_inventory', type_='unique')
    op.create_index(op.f('ix_user_inventory_is_used'), 'user_inventory', ['is_used'], unique=False)
    op.drop_column('user_inventory', 'updated_at')
    op.drop_column('user_inventory', 'quantity')
    
    # ### end Alembic commands ###
