"""add_live_bot_state_fields

Revision ID: aa2d568f3ae2
Revises: 5d73c541547e
Create Date: 2025-12-01 00:31:10.360566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa2d568f3ae2'
down_revision: Union[str, Sequence[str], None] = '5d73c541547e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('live_bots', sa.Column('mode', sa.String(length=20), nullable=False))
    op.add_column('live_bots', sa.Column('current_balance', sa.Float(), nullable=True))
    op.add_column('live_bots', sa.Column('position_size', sa.Float(), nullable=False))
    op.add_column('live_bots', sa.Column('entry_price', sa.Float(), nullable=True))
    op.add_column('live_bots', sa.Column('last_signal', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('live_bots', 'last_signal')
    op.drop_column('live_bots', 'entry_price')
    op.drop_column('live_bots', 'position_size')
    op.drop_column('live_bots', 'current_balance')
    op.drop_column('live_bots', 'mode')
    # ### end Alembic commands ###
