"""Descriptive message about your changes

Revision ID: ad54e80f67e6
Revises: 
Create Date: 2025-09-18 00:37:04.765530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad54e80f67e6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


TIMEFRAMES = ["1m", "5m", "15m", "30m", "1h", "4h", "1d", "1w", "1M"]

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    print("Creating OHLCV hypertables and indexes...")
    for tf in TIMEFRAMES:
        table_name = f"ohlcv_{tf}"
        
        # 2-1. 기본 테이블 생성
        op.create_table(
            table_name,
            sa.Column('time', sa.DateTime(timezone=True), nullable=False),
            sa.Column('ticker', sa.Text(), nullable=False),
            sa.Column('open', sa.Float(), nullable=False),
            sa.Column('high', sa.Float(), nullable=False),
            sa.Column('low', sa.Float(), nullable=False),
            sa.Column('close', sa.Float(), nullable=False),
            sa.Column('volume', sa.Float(), nullable=False),
            # Upsert를 위한 복합 기본 키 설정
            sa.PrimaryKeyConstraint('time', 'ticker')
        )
        
        # 2-2. (매우 중요) 생성된 테이블을 TimescaleDB의 하이퍼테이블로 변환
        op.execute(f"SELECT create_hypertable('{table_name}', 'time', if_not_exists => TRUE);")
        
        # 2-3. 데이터 조회 성능 최적화를 위한 복합 인덱스 생성
        op.create_index(f'idx_{table_name}_ticker_time_desc', table_name, ['ticker', sa.text('time DESC')])

        print(f"Table '{table_name}' created and converted to hypertable.")
    op.create_table('plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Enum('BASIC', 'TRADER', 'PRO', name='plantype'), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('credit_surcharge_multiplier', sa.Float(), server_default='2.0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('shop_item_details',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_type', sa.String(), nullable=False, comment='e.g., OPTIMIZATION_COUPON'),
    sa.Column('display_properties', sa.JSON(), nullable=False, comment='icon, tier, stats for UI'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_type')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bio', sa.String(length=200), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('social_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('featured_strategy_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['featured_strategy_id'], ['strategies.id'], name='fk_users_featured_strategy_id', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('exchange', sa.String(length=100), nullable=False),
    sa.Column('api_key_encrypted', sa.String(length=512), nullable=False),
    sa.Column('secret_key_encrypted', sa.String(length=512), nullable=False),
    sa.Column('api_key_preview', sa.String(length=20), nullable=True, comment='API 키 앞 4자리...뒤 4자리'),
    sa.Column('memo', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'exchange', name='_user_exchange_uc')
    )
    op.create_table('credits_attendance_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('consecutive_days', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'attendance_date', name='_user_attendance_date_uc')
    )
    op.create_index(op.f('ix_credits_attendance_logs_user_id'), 'credits_attendance_logs', ['user_id'], unique=False)
    op.create_table('credits_ledgers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False, comment='획득 경로 (e.g., PURCHASE, ATTENDANCE_DAILY)'),
    sa.Column('source_id', sa.UUID(), nullable=True, comment='관련 ID (주문 ID, 출석 로그 ID 등)'),
    sa.Column('initial_amount', sa.Integer(), nullable=False),
    sa.Column('remaining_amount', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='소멸 일시 (NULL일 경우 무기한)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credits_ledgers_user_id'), 'credits_ledgers', ['user_id'], unique=False)
    op.create_table('credits_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('total_amount_deducted', sa.Integer(), nullable=False),
    sa.Column('discount_pct', sa.Float(), nullable=False),
    sa.Column('related_entity_type', sa.String(length=50), nullable=True, comment='관련 서비스 (e.g., BACKTEST)'),
    sa.Column('related_entity_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credits_transactions_user_id'), 'credits_transactions', ['user_id'], unique=False)
    op.create_table('email_verification_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('jti', sa.String(length=255), nullable=False),
    sa.Column('hashed_token', sa.String(length=512), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'jti', name='_user_email_verif_jti_uc')
    )
    op.create_index(op.f('ix_email_verification_tokens_jti'), 'email_verification_tokens', ['jti'], unique=True)
    op.create_table('marketplace_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'CANCELED', name='orderstatus'), nullable=True),
    sa.Column('payment_gateway', sa.String(), nullable=True),
    sa.Column('gateway_transaction_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_orders_gateway_transaction_id'), 'marketplace_orders', ['gateway_transaction_id'], unique=True)
    op.create_index(op.f('ix_marketplace_orders_status'), 'marketplace_orders', ['status'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('jti', sa.String(length=255), nullable=False),
    sa.Column('hashed_token', sa.String(length=512), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'jti', name='_user_password_reset_jti_uc')
    )
    op.create_index(op.f('ix_password_reset_tokens_jti'), 'password_reset_tokens', ['jti'], unique=True)
    op.create_table('plan_features',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('max_strategies', sa.Integer(), nullable=False),
    sa.Column('max_coins_per_backtest', sa.Integer(), nullable=False),
    sa.Column('live_bots_limit', sa.Integer(), nullable=False),
    sa.Column('daily_backtest_count', sa.Integer(), nullable=False),
    sa.Column('max_backtest_duration_years', sa.Integer(), nullable=True),
    sa.Column('supported_timeframes', sa.String(), nullable=False),
    sa.Column('community_access', sa.Boolean(), nullable=False),
    sa.Column('telegram_alerts', sa.Boolean(), nullable=False),
    sa.Column('advanced_features_access', sa.Boolean(), nullable=False),
    sa.Column('portfolio_backtest_access', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('jti', sa.String(length=255), nullable=False),
    sa.Column('hashed_token', sa.String(length=512), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'jti', name='_user_jti_uc')
    )
    op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=True)
    op.create_table('social_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='_provider_user_uc')
    )
    op.create_index(op.f('ix_social_accounts_email'), 'social_accounts', ['email'], unique=True)
    op.create_table('strategies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('long_entry_rules', sa.JSON(), nullable=True),
    sa.Column('long_exit_rules', sa.JSON(), nullable=True),
    sa.Column('short_entry_rules', sa.JSON(), nullable=True),
    sa.Column('short_exit_rules', sa.JSON(), nullable=True),
    sa.Column('tpsl_logic', sa.JSON(), nullable=True),
    sa.Column('target_coins', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('paid_feature_level', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_gateway_customer_key', sa.String(length=255), nullable=True, comment='PG사 빌링키 (Toss 등)'),
    sa.Column('payment_method_details', sa.String(length=255), nullable=True, comment='카드 정보 요약 (현대카드 1234)'),
    sa.Column('payment_gateway_sub_id', sa.String(length=255), nullable=True),
    sa.Column('refresh_token', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_gateway_sub_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('backtests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('celery_task_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELED', name='backteststatus'), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('strategy_snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtests_celery_task_id'), 'backtests', ['celery_task_id'], unique=False)
    op.create_table('credits_transaction_details',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('ledger_id', sa.UUID(), nullable=False),
    sa.Column('amount_deducted', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ledger_id'], ['credits_ledgers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['credits_transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('live_bots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('api_key_id', sa.UUID(), nullable=False),
    sa.Column('celery_task_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('initial_capital', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_bots_celery_task_id'), 'live_bots', ['celery_task_id'], unique=False)
    op.create_table('backtest_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('backtest_id', sa.UUID(), nullable=False),
    sa.Column('total_return_pct', sa.Float(), nullable=True),
    sa.Column('mdd_pct', sa.Float(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('win_rate_pct', sa.Float(), nullable=True),
    sa.Column('pnl_curve_json', sa.JSON(), nullable=True),
    sa.Column('drawdown_curve_json', sa.JSON(), nullable=True),
    sa.Column('trade_summary_json', sa.JSON(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('sortino_ratio', sa.Float(), nullable=True),
    sa.Column('cagr_pct', sa.Float(), nullable=True),
    sa.Column('calmar_ratio', sa.Float(), nullable=True),
    sa.Column('ulcer_index', sa.Float(), nullable=True),
    sa.Column('avg_profit_loss_ratio', sa.Float(), nullable=True),
    sa.Column('k_ratio', sa.Float(), nullable=True),
    sa.Column('longest_flat_days', sa.Integer(), nullable=True),
    sa.Column('avg_holding_period_days', sa.Float(), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('winning_trades', sa.Integer(), nullable=True),
    sa.Column('losing_trades', sa.Integer(), nullable=True),
    sa.Column('backtest_score', sa.Float(), nullable=True),
    sa.Column('score_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['backtest_id'], ['backtests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('backtest_id')
    )
    op.create_table('community_posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('backtest_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['backtest_id'], ['backtests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('backtest_id')
    )
    op.create_index(op.f('ix_community_posts_created_at'), 'community_posts', ['created_at'], unique=False)
    op.create_table('marketplace_products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('product_type', sa.Enum('STRATEGY', 'SHOP_ITEM', name='producttype'), nullable=False),
    sa.Column('inventory_type', sa.Enum('UNLOCK', 'CONSUMABLE', name='inventorytype'), nullable=False),
    sa.Column('linked_resource_id', sa.UUID(), nullable=False, comment='strategies.id or shop_item_details.id'),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('representative_backtest_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['representative_backtest_id'], ['backtests.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_products_linked_resource_id'), 'marketplace_products', ['linked_resource_id'], unique=False)
    op.create_index(op.f('ix_marketplace_products_product_type'), 'marketplace_products', ['product_type'], unique=False)
    op.create_table('trade_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('backtest_id', sa.UUID(), nullable=True),
    sa.Column('live_bot_id', sa.UUID(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('current_balance', sa.Float(), nullable=True),
    sa.Column('reason', sa.String(length=50), nullable=True),
    sa.CheckConstraint('(backtest_id IS NOT NULL AND live_bot_id IS NULL) OR (backtest_id IS NULL AND live_bot_id IS NOT NULL)', name='_trade_log_exclusive_parent_check'),
    sa.ForeignKeyConstraint(['backtest_id'], ['backtests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['live_bot_id'], ['live_bots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_logs_timestamp'), 'trade_logs', ['timestamp'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('likes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'post_id', name='_user_post_uc')
    )
    op.create_table('marketplace_order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price_at_purchase', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['marketplace_orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['marketplace_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_inventory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['marketplace_products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_id', name='_user_product_uc')
    )
    op.create_index(op.f('ix_user_inventory_user_id'), 'user_inventory', ['user_id'], unique=False)
    op.create_table('user_purchased_strategies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('order_item_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_item_id'], ['marketplace_order_items.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'strategy_id', name='_user_strategy_uc')
    )
    op.create_index(op.f('ix_user_purchased_strategies_strategy_id'), 'user_purchased_strategies', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_user_purchased_strategies_user_id'), 'user_purchased_strategies', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_purchased_strategies_user_id'), table_name='user_purchased_strategies')
    op.drop_index(op.f('ix_user_purchased_strategies_strategy_id'), table_name='user_purchased_strategies')
    op.drop_table('user_purchased_strategies')
    op.drop_index(op.f('ix_user_inventory_user_id'), table_name='user_inventory')
    op.drop_table('user_inventory')
    op.drop_table('marketplace_order_items')
    op.drop_table('likes')
    op.drop_table('comments')
    op.drop_index(op.f('ix_trade_logs_timestamp'), table_name='trade_logs')
    op.drop_table('trade_logs')
    op.drop_index(op.f('ix_marketplace_products_product_type'), table_name='marketplace_products')
    op.drop_index(op.f('ix_marketplace_products_linked_resource_id'), table_name='marketplace_products')
    op.drop_table('marketplace_products')
    op.drop_index(op.f('ix_community_posts_created_at'), table_name='community_posts')
    op.drop_table('community_posts')
    op.drop_table('backtest_results')
    op.drop_index(op.f('ix_live_bots_celery_task_id'), table_name='live_bots')
    op.drop_table('live_bots')
    op.drop_table('credits_transaction_details')
    op.drop_index(op.f('ix_backtests_celery_task_id'), table_name='backtests')
    op.drop_table('backtests')
    op.drop_table('subscriptions')
    op.drop_table('strategies')
    op.drop_index(op.f('ix_social_accounts_email'), table_name='social_accounts')
    op.drop_table('social_accounts')
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('plan_features')
    op.drop_index(op.f('ix_password_reset_tokens_jti'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_marketplace_orders_status'), table_name='marketplace_orders')
    op.drop_index(op.f('ix_marketplace_orders_gateway_transaction_id'), table_name='marketplace_orders')
    op.drop_table('marketplace_orders')
    op.drop_index(op.f('ix_email_verification_tokens_jti'), table_name='email_verification_tokens')
    op.drop_table('email_verification_tokens')
    op.drop_index(op.f('ix_credits_transactions_user_id'), table_name='credits_transactions')
    op.drop_table('credits_transactions')
    op.drop_index(op.f('ix_credits_ledgers_user_id'), table_name='credits_ledgers')
    op.drop_table('credits_ledgers')
    op.drop_index(op.f('ix_credits_attendance_logs_user_id'), table_name='credits_attendance_logs')
    op.drop_table('credits_attendance_logs')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('shop_item_details')
    op.drop_table('plans')
    # 3. 모든 하이퍼테이블을 삭제하는 수동 스크립트를 추가합니다.
    print("Dropping OHLCV hypertables...")
    for tf in TIMEFRAMES:
        table_name = f"ohlcv_{tf}"
        op.drop_table(table_name)
        print(f"Table '{table_name}' dropped.")
    # ### end Alembic commands ###