"""Add billing fields to subscription

Revision ID: bb94b2777895
Revises: 7e32d4d5443b
Create Date: 2025-09-04 09:00:45.883522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb94b2777895'
down_revision: Union[str, Sequence[str], None] = '7e32d4d5443b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('payment_gateway_customer_key', sa.String(length=255), nullable=True, comment='PG사 빌링키 (Toss 등)'))
    op.add_column('subscriptions', sa.Column('payment_method_details', sa.String(length=255), nullable=True, comment='카드 정보 요약 (현대카드 1234)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'payment_method_details')
    op.drop_column('subscriptions', 'payment_gateway_customer_key')
    # ### end Alembic commands ###
