"""add_profile_fields_to_user

Revision ID: bbe3a66c2fdf
Revises: e9fe46353a83
Create Date: 2025-09-13 22:54:37.528660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bbe3a66c2fdf'
down_revision: Union[str, Sequence[str], None] = 'e9fe46353a83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.alter_column('api_keys', 'api_key_preview',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_comment='API 키 앞 4자리...뒤 4자리',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.alter_column('api_keys', 'api_key_preview',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_comment='API 키 앞 4자리...뒤 4자리',
               existing_nullable=True)
    
    # ### end Alembic commands ###
