"""add_live_bot_extended_fields

Revision ID: c60503499d80
Revises: aa2d568f3ae2
Create Date: 2025-12-01 01:16:35.590254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c60503499d80'
down_revision: Union[str, Sequence[str], None] = 'aa2d568f3ae2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('live_bots', sa.Column('ticker', sa.String(length=20), server_default='BTCUSDT', nullable=False))
    op.add_column('live_bots', sa.Column('leverage', sa.Float(), nullable=False))
    op.add_column('live_bots', sa.Column('daily_max_loss_pct', sa.Float(), nullable=True, comment='일일 최대 손실 %'))
    op.add_column('live_bots', sa.Column('daily_max_loss_enabled', sa.Boolean(), nullable=False))
    op.add_column('live_bots', sa.Column('daily_pnl', sa.Float(), nullable=False, comment='오늘 누적 손익'))
    op.add_column('live_bots', sa.Column('daily_pnl_reset_date', sa.Date(), nullable=True, comment='마지막 리셋 날짜'))
    op.add_column('live_bots', sa.Column('total_trades', sa.Integer(), nullable=False))
    op.add_column('live_bots', sa.Column('winning_trades', sa.Integer(), nullable=False))
    op.add_column('live_bots', sa.Column('total_pnl', sa.Float(), nullable=False))
    op.add_column('live_bots', sa.Column('max_drawdown', sa.Float(), nullable=False))
    op.add_column('live_bots', sa.Column('peak_balance', sa.Float(), nullable=True, comment='최고 잔고 (MDD 계산용)'))
    op.add_column('live_bots', sa.Column('sl_price', sa.Float(), nullable=True, comment='Stop Loss 가격'))
    op.add_column('live_bots', sa.Column('tp_price', sa.Float(), nullable=True, comment='Take Profit 가격'))
    op.add_column('live_bots', sa.Column('trailing_stop_activation_price', sa.Float(), nullable=True, comment='Trailing Stop 활성화 가격'))
    op.add_column('live_bots', sa.Column('last_error', sa.Text(), nullable=True))
    op.add_column('live_bots', sa.Column('error_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('live_bots', 'error_count')
    op.drop_column('live_bots', 'last_error')
    op.drop_column('live_bots', 'trailing_stop_activation_price')
    op.drop_column('live_bots', 'tp_price')
    op.drop_column('live_bots', 'sl_price')
    op.drop_column('live_bots', 'peak_balance')
    op.drop_column('live_bots', 'max_drawdown')
    op.drop_column('live_bots', 'total_pnl')
    op.drop_column('live_bots', 'winning_trades')
    op.drop_column('live_bots', 'total_trades')
    op.drop_column('live_bots', 'daily_pnl_reset_date')
    op.drop_column('live_bots', 'daily_pnl')
    op.drop_column('live_bots', 'daily_max_loss_enabled')
    op.drop_column('live_bots', 'daily_max_loss_pct')
    op.drop_column('live_bots', 'leverage')
    op.drop_column('live_bots', 'ticker')
    # ### end Alembic commands ###
