"""add_profile_fields_to_user

Revision ID: e9fe46353a83
Revises: 8623cc6bf52d
Create Date: 2025-09-13 22:47:02.378618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e9fe46353a83'
down_revision: Union[str, Sequence[str], None] = '8623cc6bf52d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('api_keys', sa.Column('api_key_preview', sa.String(length=10), nullable=True, comment='API 키 앞 4자리...뒤 4자리'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_column('api_keys', 'api_key_preview')
    
    # ### end Alembic commands ###
