"""add task_type to ai_model

Revision ID: efb06f6ce711
Revises: 0089d4c09d56
Create Date: 2025-12-29 06:41:17.747996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'efb06f6ce711'
down_revision: Union[str, Sequence[str], None] = '0089d4c09d56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('ai_models', sa.Column('task_type', sa.String(length=50), nullable=True))
    op.execute("UPDATE ai_models SET task_type = 'classification' WHERE task_type IS NULL")
    op.alter_column('ai_models', 'task_type', nullable=False)
    op.alter_column('ai_models', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_models', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('ai_models', 'task_type')
    
    # ### end Alembic commands ###
